import type {Metadata} from 'next';
import {headers} from 'next/headers';
import {LanguageSwitcher} from '@/components/language-switcher';
import {localeFromPath,localizedPath,withoutLocale,translate} from '@/lib/i18n';
import './globals.css';
import './fit.css';
import './landing.css';
export async function generateMetadata():Promise<Metadata>{const h=await headers();const path=h.get('x-tokfire-path')||'/';const locale=localeFromPath(path);const plain=withoutLocale(path);const title=plain==='/methodology'?'Read the methodology & limitations':plain==='/signin'?'Sign in':plain==='/native-connect'?'Connect TokFire Bench':'TokFire Bench';const description=translate('Benchmark GGUF or MLX models, choose 1–3 concurrent jobs calling one model, and upload results without signing in.',locale);return {metadataBase:new URL('https://tokfires.com'),title:translate(title,locale)+' | TokFire Labs',description,applicationName:'TokFire Bench',authors:[{name:'TokFire Labs'}],alternates:{canonical:localizedPath(plain,locale),languages:{en:localizedPath(plain,'en'),'zh-Hant':localizedPath(plain,'zh-Hant'),'zh-Hans':localizedPath(plain,'zh-Hans'),'x-default':localizedPath(plain,'en')}},robots:plain==='/signin'||plain==='/native-connect'?{index:false,follow:false}:undefined,openGraph:{title:'TokFire Bench',description,siteName:'TokFire',images:[{url:'/images/tokfire-local-ai.jpg',width:1536,height:1024,alt:'TokFire Bench — local AI on your hardware'}],type:'website',locale:locale==='zh-Hant'?'zh_TW':locale==='zh-Hans'?'zh_CN':'en_US'},icons:{icon:'/favicon.svg',shortcut:'/favicon.svg'}};}
export default async function RootLayout({children}:{children:React.ReactNode}){const h=await headers();const locale=localeFromPath(h.get('x-tokfire-path')||'/');return <html lang={locale}><body className="antialiased"><LanguageSwitcher/>{children}</body></html>;}
