'use client';
/* eslint-disable @next/next/no-html-link-for-pages -- Public links also work on the script-free mirror. */
import {ArrowUpRight, Cpu, Monitor} from 'lucide-react';
import {localizeTree} from '@/lib/i18n';
import {useLocale} from './language-switcher';
const gguf='https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF';
const mlx='https://huggingface.co/mlx-community/Qwen3.8-27B-4bit';
export const hardwarePicks=[
 {id:'pc-entry',platform:'PC',tag:'The accessible starting point',name:'RTX 5060 Ti',memory:'16 GB VRAM',spec:'32 GB RAM · 1 TB NVMe',cpu:'Modern 6–8 core CPU',format:'GSQ-RCO IQ3_S · GGUF',size:'11.8 GB',runtime:'llama.cpp · CUDA',intent:'Start with chat, then one tool job',reason:'A compact 27B quant makes a 16 GB gaming GPU worth testing. Choose the 16 GB card, not the 8 GB variant.',start:'1 job · 4K context',source:'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5060-family/',model:gguf},
 {id:'pc-existing',platform:'PC',tag:'Make more of an existing rig',name:'RTX 4090',memory:'24 GB VRAM',spec:'64 GB RAM · 2 TB NVMe',cpu:'Modern 8+ core CPU',format:'GSQ-RCO IQ3_S · GGUF',size:'11.8 GB',runtime:'llama.cpp · CUDA',intent:'Test single-job agent workflows',reason:'Already own a 24 GB GPU? Keep it. The same compact model leaves more capacity for context and runtime buffers.',start:'1 job · 8K context',source:'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/',model:gguf},
 {id:'pc-headroom',platform:'PC',tag:'Explore parallel workloads',name:'RTX 5090',memory:'32 GB VRAM',spec:'64 GB RAM · 2 TB NVMe',cpu:'Modern 8+ core CPU',format:'GSQ-RCO IQ3_S · GGUF',size:'11.8 GB',runtime:'llama.cpp · CUDA',intent:'Candidate for a 1 → 2 → 3 job sweep',reason:'The largest VRAM option here gives more room to explore concurrent jobs. Measure per-job latency before treating it as a shared server.',start:'1 job · 8K context',source:'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/',model:gguf},
 {id:'mac-entry',platform:'Mac',tag:'A compact local AI desk',name:'Mac mini · M5 Pro',memory:'48 GB unified',spec:'1 TB SSD',cpu:'18-core CPU · 20-core GPU',format:'MLX community · 4-bit',size:'16.1 GB',runtime:'oMLX · MLX',intent:'Start with chat, then one tool job',reason:'Unified memory gives the model and macOS a shared pool. A 48 GB configuration is a sensible starting point for this 4-bit model.',start:'1 job · 4K context',source:'https://www.apple.com/mac-mini/specs/',model:mlx},
 {id:'mac-balanced',platform:'Mac',tag:'The everyday workstation',name:'Mac Studio · M5 Max',memory:'64 GB unified',spec:'1 TB SSD',cpu:'18-core CPU · 40-core GPU',format:'MLX community · 4-bit',size:'16.1 GB',runtime:'oMLX · MLX',intent:'Test single-job agent workflows',reason:'More memory for a longer working conversation and other desktop apps. Test a second job only after your single-job baseline passes.',start:'1 job · 8K context',source:'https://www.apple.com/mac-studio/specs/',model:mlx},
 {id:'mac-headroom',platform:'Mac',tag:'Room for a shared AI service',name:'Mac Studio · M5 Ultra',memory:'96 GB unified',spec:'2 TB SSD',cpu:'30-core CPU · 64-core GPU',format:'MLX community · 4-bit',size:'16.1 GB',runtime:'oMLX · MLX',intent:'Candidate for a 1 → 2 → 3 job sweep',reason:'Extra capacity makes this a candidate for parallel experiments. It does not prove that every job will stay responsive.',start:'1 job · 8K context',source:'https://www.apple.com/mac-studio/specs/',model:mlx},
] as const;
export function HardwarePicks({compact=false}:{compact?:boolean}){const locale=useLocale();return localizeTree(<section className={`hardware-picks ${compact?'picks-compact':''}`} id="setups" aria-labelledby="picks-title">
 <div className="landing-section-head"><div><span className="landing-kicker">THE QWEN3.8-27B SHORTLIST</span><h2 id="picks-title">One model. Six ways in.</h2></div><p>Three PC builds. Three Macs. Curated starting configurations based on published model sizes and hardware specifications—not measured rankings.</p></div>
 <div className="picks-platform-nav"><a href="#pc-picks"><Monitor size={16}/>PC / NVIDIA</a><a href="#mac-picks"><Cpu size={16}/>Mac / Apple silicon</a><span>Reviewed 16 Sep 2026</span></div>
 {(['PC','Mac'] as const).map(platform=><div className="picks-group" key={platform} id={platform==='PC'?'pc-picks':'mac-picks'}><h3 className="picks-group-title">{platform==='PC'?'PC · compact GGUF weights':'Mac · native MLX weights'}</h3><div className="picks-grid">{hardwarePicks.filter(p=>p.platform===platform).map((p,i)=><article className="pick-card" key={p.id}>
  <div className="pick-top"><span>{p.tag}</span><span className="pick-number">0{i+1}</span></div><div className="pick-device">{platform==='PC'?<Monitor size={31}/>:<Cpu size={31}/>}<span>{p.memory}</span></div><h3>{p.name}</h3><p className="pick-spec">{p.cpu}<br/>{p.spec}</p>
  <div className="pick-model"><span>Qwen3.8-27B</span><b>{p.format}</b><small>{p.size} <span>published download size</span></small><small className="pick-runtime">{p.runtime}</small></div><p className="pick-reason">{p.reason}</p><div className="pick-target"><span>Suggested test</span><b>{p.intent}</b><small>{p.start}</small></div>
  <div className="pick-evidence"><span>U</span><small>Fit grade pending measurement</small></div><div className="pick-links"><a href={p.model} target="_blank" rel="noreferrer">Get model <ArrowUpRight size={14}/></a><a href={p.source} target="_blank" rel="noreferrer">Hardware specs <ArrowUpRight size={14}/></a></div>
 </article>)}</div></div>)}
 <div className="picks-note"><b>Memory fit is the beginning.</b><p>Download size is not total memory use. Leave room for the OS, runtime, vision components and KV cache—the model’s working memory. Context and concurrent jobs increase demand. These starter settings are experiments, not a guarantee of speed or agent success. Use a runtime that supports this model; TokFire has not validated these six combinations yet.</p><a href="/#download">Test your own setup →</a></div>
 </section>,locale);}
