'use client';
/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Static mirror needs ordinary image and document links. */
import {ArrowRight, ArrowUpRight, Download, Flame, Layers3, LockKeyhole, SlidersHorizontal, Zap} from 'lucide-react';
import {localizeTree} from '@/lib/i18n';
import {useLocale} from './language-switcher';
import {HardwarePicks} from './hardware-picks';
export function LandingNav(){const locale=useLocale();return localizeTree(<header className="landing-nav"><a className="landing-brand" href="/" aria-label="TokFire home"><Flame/><span>TokFire<span className="brand-product"> / Bench</span></span></a><nav aria-label="Explore TokFire"><a href="/#why-local">Why local AI</a><a href="/#setups">Find your setup</a><a href="/?tab=rankings">Rankings & fit</a><a href="/blog">Blogs & tutorials</a><a href="/?tab=privacy">My data</a></nav><a className="landing-nav-cta" href="/#download">Get the app <ArrowUpRight size={15}/></a></header>,locale);}
export function LandingPage(){const locale=useLocale();return localizeTree(<div className="landing">
 <section className="landing-hero"><img className="landing-hero-image" src="/images/tokfire-local-ai.jpg" alt="Concept illustration of a compact desktop and gaming PC lit in warm orange" width={1536} height={1024} fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><span className="landing-kicker"><i/> YOUR HARDWARE. YOUR AI.</span><h1>Big intelligence.<br/>Closer to home.</h1><p>A gaming PC. A compact Mac. Your next AI workspace might already be on your desk. Find the model that fits—and measure what it can actually do.</p><div className="hero-actions"><a className="landing-primary" href="#download">Test my machine <ArrowRight size={18}/></a><a className="landing-secondary" href="#setups">Explore 6 setups <ArrowUpRight size={18}/></a></div><span className="hero-caption">TokFire Bench · Free 1–3 concurrent jobs · No login needed</span></div><div className="hero-image-caption">Concept hardware illustration</div><div className="hero-bottom"><span>LOCAL MODELS.<br/><b>REAL POSSIBILITIES.</b></span><div><span>PC</span><i/> <span>Mac</span><i/> <span>GGUF</span><i/> <span>MLX</span></div></div></section>
 <section className="landing-proof"><div><strong>27B</strong><span>A capable model class,<br/>within reach of personal hardware.</span></div><div><strong>11.8<span> GB</span></strong><span>Published GSQ-RCO IQ3_S file size.<br/>Runtime memory is additional.</span></div><div><strong>1 → 3</strong><span>Concurrent jobs to test.<br/>Find where your setup stays useful.</span></div></section>
 <section className="landing-why" id="why-local"><div className="landing-section-head"><div><span className="landing-kicker">WHY LOCAL. WHY NOW.</span><h2>Your AI should feel<br/>like your computer.</h2></div><p>Smaller model files open the door to useful local AI. Choose your model, keep inference close to your files, and put the hardware you own to work.</p></div><div className="why-grid">{[[LockKeyhole,'Keep your work close','Run inference on your own machine. Offline local workflows can keep prompts and documents on-device; connected tools have their own data flows.'],[SlidersHorizontal,'Choose how it runs','Pick your model, context and runtime. Keep a working version for your workflows and change it on your schedule.'],[Zap,'Put your GPU to work','Use the same machine for coding, document work and chat. Local inference avoids per-token API billing, with hardware and electricity costs still yours.']].map(([Icon,title,body])=>{const I=Icon as typeof Zap;return <article key={String(title)}><I size={25}/><h3>{String(title)}</h3><p>{String(body)}</p></article>;})}</div></section>
 <section className="model-story"><div><span className="landing-kicker">THE 16 GB OPPORTUNITY</span><h2>27 billion parameters.<br/><em>A much smaller footprint.</em></h2><p>ISTA-DASLab’s GSQ + RCO quantization allocates precision unevenly across a model. Its Qwen3.8-27B IQ3_S file is 11.8 GB, making a 16 GB GPU an interesting place to start.</p><p>The authors report near-baseline results on selected tests. This is compressed precision—not the original full-precision model, and not a promise of identical answers.</p><a href="https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF" className="landing-source" target="_blank" rel="noreferrer">Read the model evidence <ArrowUpRight size={16}/></a></div><div className="memory-visual"><span>MODEL FILE SIZE / GB</span><div className="memory-bar"><div className="bar-label"><span>BF16</span><b>53.8</b></div><i style={{width:'100%'}}/></div><div className="memory-bar quant"><div className="bar-label"><span>GSQ-RCO IQ3_S</span><b>11.8</b></div><i style={{width:'22%'}}/></div><div className="memory-extra"><Layers3/><p>Then add working memory.<small>KV cache + runtime buffers + optional vision / MTP components</small></p></div><span className="memory-foot">Published file sizes · not measured VRAM usage</span></div></section>
 <HardwarePicks/>
 <section className="landing-workflow"><div className="landing-section-head"><div><span className="landing-kicker">FROM “IT FITS” TO “IT WORKS”</span><h2>Find your useful limit.</h2></div><p>Fast text generation is only one part of the story. TokFire measures the wait, the completed work and what changes when jobs overlap.</p></div><div className="workflow-grid">{[['01','Start with one job','Run chat, business, document or a local agent-tool workload. Capture completion, first output and task latency.'],['02','Turn up the concurrency','Repeat with 2 or 3 jobs calling the same model. Watch per-job responsiveness and failures, not just combined throughput.'],['03','Make the result useful','Read the workload-fit grade. Save the report locally, upload as a guest, and choose separately whether to publish it.']].map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><a className="landing-secondary" href="/?tab=rankings">See recommendations & public results <ArrowRight size={17}/></a></section>
 <section className="landing-learn"><div><span className="landing-kicker">LEARN / BUILD / MEASURE</span><h2>Make local AI part of your day.</h2><p>Six practical guides: your first assistant, private document Q&amp;A, Mac MLX, GPU memory, tool agents and concurrent jobs.</p></div><a className="landing-secondary" href="/blog">Explore the guides <ArrowRight size={17}/></a></section>
 <section className="landing-download" id="download"><div><span className="landing-kicker">TOKFIRE BENCH / 0.7 PREVIEW</span><h2>Let your machine<br/>do the talking.</h2><p>Start free with 1–3 concurrent jobs on one model. Pro is planned at HK$180 once for up to 20 jobs on one activated device; paid release awaits store approval.</p><a href="/methodology" className="landing-source">Methodology & limitations <ArrowUpRight size={16}/></a></div><div className="download-grid"><a href="/TokFireBench-0.7.0-macos-arm64.dmg" download><Download/><b>macOS</b><span>Apple silicon · DMG</span><ArrowUpRight/></a><a href="/TokFireBench-0.7.0-windows-x64.zip" download><Download/><b>Windows</b><span>x64 · ZIP preview</span><ArrowUpRight/></a><a href="/TokFireBench-0.7.0-cli.tar.gz" download><Download/><b>Linux / CLI</b><span>Cross-platform runner</span><ArrowUpRight/></a><a href="/TokFireBench-0.7.0-android-preview.apk" download><Download/><b>Android</b><span>Native client · APK preview</span><ArrowUpRight/></a></div><details className="download-details"><summary>Before you install</summary><p>Install Python and a compatible inference runtime separately. Mac supports GGUF with llama.cpp or MLX with oMLX. Optional MTP requires a compatible runtime and extra configuration; TokFire does not enable it automatically.</p><p>The Mac DMG is ad-hoc signed, not notarized. Windows is unsigned; native Windows/GPU testing is pending. Android connects to an existing on-device or LAN runtime; it does not bundle a model engine. Physical-phone validation is pending.</p><p>Automatic upload is on before Run and can be disabled. Public sharing is separate and off by default. Failed uploads stay queued; reports are saved locally. The agent workload checks a local tool fixture, not a complete browser-agent product.</p><a href="/tokfire-bench-source.zip" download>Download source</a><a href="/native-connect">Connect the desktop app →</a></details></section>
 </div>,locale);}
