'use client';
import {useEffect,useState} from 'react';
import type {ArchiveReport} from '@/lib/public-archive';
import {localizeTree} from '@/lib/i18n';
import {useLocale} from './language-switcher';
const names:Record<string,string>={'local-ai-text-v1':'Standard token benchmark','local-ai-trial-v1':'Short trial · not ranked','local-ai-jobs-v1':'Concurrent jobs benchmark','local-ai-windows-jobs-v1':'Windows concurrent jobs','local-ai-omlx-v1':'App oMLX concurrency sweep'};
export function PublicArchive(){const locale=useLocale();const [reports,setReports]=useState<ArchiveReport[]>([]);const [status,setStatus]=useState('Loading measurements…');
 useEffect(()=>{let active=true;fetch('/api/v2/archive').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{results:ArchiveReport[]}>;}).then(r=>{if(active){setReports(r.results);setStatus('');}}).catch(()=>{if(active)setStatus('Comparison data is temporarily unavailable. Please reload.');});return()=>{active=false;};},[]);
 return localizeTree(<section className="panel fit-section" id="archive"><div className="fit-section-head"><div><span className="fit-eyebrow">EARLIER APP MEASUREMENTS</span><h2>Every published test has a place.</h2><p>Earlier app reports use different test profiles. These measurements are public, but are not mixed into 0.7 workload grades. oMLX entries here are tests run in the TokFire app, not imported third-party records.</p></div><span className="archive-count">{reports.length} <span>reports</span></span></div>
 {status?<p role="status">{status}</p>:!reports.length?<p>No earlier public reports yet.</p>:reports.map(r=><article className="archive-report" key={r.runId}><header><div><span>{names[r.spec]??r.spec}</span><h3 data-no-translate>{r.chip} · {(r.memoryBytes/2**30).toFixed(0)} GiB</h3></div><span data-no-translate>{r.runtime} · {r.measuredAt.slice(0,10)}</span></header>{r.models.map(m=><div key={m.name}><h4 data-no-translate>{m.name}</h4><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Concurrent jobs</th><th>Input tokens</th><th>Samples</th><th>Median decode</th><th>Median first output</th><th>Agent fit</th></tr></thead><tbody>{m.rows.map((row,i)=><tr key={i}><td>{row.jobs}</td><td>{row.inputTokens??'Variable'}</td><td>{row.samples}</td><td>{row.decodeTps.toFixed(1)} tok/s</td><td>{(row.ttftMs/1000).toFixed(2)} s</td><td>Not tested</td></tr>)}</tbody></table></div></div>)}<p className="fit-footnote">Self-reported timing. Medians can hide slow requests; these profiles do not establish agent-task success.</p></article>)}
 </section>,locale);
}
