import data from './blog-posts.json';
import type {Locale} from './i18n';
export const posts=data.posts;
export type BlogPost=typeof posts[number];
export const sources:Record<string,{label:string;url:string}>=data.sources;
export const getPost=(slug:string)=>posts.find(post=>post.slug===slug);
export function blogText(locale:Locale){return {
 en:{title:'Local AI, put to work.',label:'THE TOKFIRE FIELD GUIDE',intro:'Six practical guides for the hardware on your desk. Build something useful, understand the technology, and measure what actually works.',all:'Blogs & tutorials',start:'Start here',read:'Read the guide',minutes:'min read',reviewed:'Sources reviewed',author:'TokFire Labs',contents:'In this guide',outcome:'What you will build or learn',sources:'Sources',code:'Complete example',download:'Download Python example',exampleNote:'Teaching code with fictional data. Requires the local runtime and models described above; model outputs vary. These examples are not published benchmark results.',related:'Keep exploring',cta:'Put your setup to the test.',ctabody:'Measure one model with 1, 2 or 3 concurrent jobs. See what stays responsive on your hardware.',app:'Get TokFire Bench',results:'Explore measured results',back:'All guides',date:'16 September 2026',tags:{start:'GETTING STARTED',rag:'PRIVATE KNOWLEDGE',mac:'APPLE SILICON',memory:'MODEL FIT',agent:'AGENT WORKFLOWS',speed:'PERFORMANCE'}},
 'zh-Hant':{title:'讓本地 AI，真正幫到手。',label:'TOKFIRE 實用指南',intro:'六篇實用教學，從桌上的硬件開始。建立有用的工具、理解技術，再量度實際表現。',all:'文章與教學',start:'由這裏開始',read:'閱讀教學',minutes:'分鐘閱讀',reviewed:'來源核實日期',author:'TokFire Labs',contents:'本篇目錄',outcome:'你會建立或學到甚麼',sources:'資料來源',code:'完整範例',download:'下載 Python 範例',exampleNote:'使用虛構資料的教學程式，須先安裝文中所述本地執行環境及模型；模型輸出可能不同。這些範例不是已公開的測試成績。',related:'繼續探索',cta:'試出你的配置能做到甚麼。',ctabody:'以 1、2 或 3 個並行 job 測試同一模型，找出你的硬件能保持順暢的工作負載。',app:'下載 TokFire Bench',results:'查看實測結果',back:'所有教學',date:'2026 年 9 月 16 日',tags:{start:'開始使用',rag:'私人知識庫',mac:'APPLE SILICON',memory:'模型配搭',agent:'AGENT 工作流程',speed:'效能測試'}},
 'zh-Hans':{title:'让本地 AI，真正帮上忙。',label:'TOKFIRE 实用指南',intro:'六篇实用教程，从桌上的硬件开始。创建有用的工具、理解技术，再测量实际表现。',all:'文章与教程',start:'从这里开始',read:'阅读教程',minutes:'分钟阅读',reviewed:'来源核实日期',author:'TokFire Labs',contents:'本篇目录',outcome:'你会创建或学到什么',sources:'资料来源',code:'完整示例',download:'下载 Python 示例',exampleNote:'使用虚构数据的教学程序，须先安装文中所述本地运行环境及模型；模型输出可能不同。这些示例不是已公开的测试成绩。',related:'继续探索',cta:'试出你的配置能做到什么。',ctabody:'以 1、2 或 3 个并发 job 测试同一模型，找出你的硬件能保持流畅的工作负载。',app:'下载 TokFire Bench',results:'查看实测结果',back:'所有教程',date:'2026 年 9 月 16 日',tags:{start:'开始使用',rag:'私人知识库',mac:'APPLE SILICON',memory:'模型搭配',agent:'AGENT 工作流程',speed:'性能测试'}}
 }[locale];}
