'use client';
import {useEffect,useState} from 'react';
type Row={kind:string;sourceUrl:string;fetchedAt:string;coverage:string;rowJson:string};
export default function References(){const [rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState('Loading…'),[kind,setKind]=useState('performance'),[query,setQuery]=useState('');
 async function load(){try{const r=await fetch('/api/v1/references');const d=await r.json() as {error?:string;results:Row[]};if(!r.ok)throw Error(d.error);setRows(d.results);setStatus(d.results.length+' imported reference records');}catch{setStatus('Reference database unavailable. Please retry.');}}
 async function sync(){setStatus('Importing reviewed snapshot…');try{const r=await fetch('/api/v1/references',{method:'POST'});if(!r.ok)throw Error();await load();}catch{setStatus('Import failed. Sign in and retry.');}}
 useEffect(()=>{void sync();},[]);
 return <main style={{maxWidth:1300,margin:'40px auto',padding:24}}><a href="/">← TokFire Bench</a><h1>oMLX reference library</h1><p>Public community reports, attributed to oMLX. External reference data has not been independently verified and is kept separate from local benchmark cohorts.</p><p>{status}</p><button onClick={sync}>Import / refresh bundled snapshot</button> <button onClick={load}>Reload database</button><p>{rows[0]?.coverage}</p><p>Snapshot fetched: {rows[0]?.fetchedAt??'Not imported'}</p><select value={kind} onChange={e=>setKind(e.target.value)}><option>performance</option><option>intelligence</option></select> <input placeholder="Filter model or chip" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{overflowX:'auto'}}><table style={{width:'100%',marginTop:20}}><thead><tr>{(kind==='performance'?['Source','Chip','RAM','Model','Quant','Context','PP tok/s','TG tok/s','Notes','Date']:['Source','Author','Model','Quant','Benchmark','Score','Samples','Notes','Date']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.filter(r=>r.kind===kind&&r.rowJson.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(JSON.parse(a.rowJson).cells[0])-Number(JSON.parse(b.rowJson).cells[0])).map(r=>{const d=JSON.parse(r.rowJson);return <tr key={r.sourceUrl}>{d.cells.map((cell:string,i:number)=><td style={{padding:'10px 6px',borderBottom:'1px solid #ddd'}} key={i}>{i===0?<a href={r.sourceUrl} target="_blank" rel="noreferrer">oMLX ↗</a>:i===d.cells.length-2&&kind==='performance'?d.tips.filter((s:string)=>!s.includes('(GMT)')&&s!==d.cells[3]).join('; '):i===d.cells.length-1?(d.tips.find((s:string)=>s.includes('(GMT)'))??cell):cell}</td>)}</tr>})}</tbody></table></div></main>;
}
